---
- name: Install fzf key bindings
  ansible.builtin.command:
    cmd: "{{ brew_prefix.stdout }}/opt/fzf/install --key-bindings --completion --no-update-rc"
    creates: "{{ home_dir }}/.fzf.zsh"
  tags: [dev-tools, fzf]

- name: Create ~/personal directory
  ansible.builtin.file:
    path: "{{ home_dir }}/personal"
    state: directory
    mode: "0755"
  tags: [dev-tools, directories]

- name: Create ~/work directory
  ansible.builtin.file:
    path: "{{ home_dir }}/work"
    state: directory
    mode: "0755"
  tags: [dev-tools, directories]
